export const UPDATE_AUTH = 'UPDATE_AUTH';
// export const LOGOUT = 'LOGOUT';
// export const TOGGLE_LOGINFORM = 'TOGGLE_LOGINFORM';
// export const HIDE_LOGINFORM = 'HIDE_LOGINFORM';
// export const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';
// export const UPDATE_MOVIE = 'UPDATE_MOVIE';
// export const FETCHING_MOVIES = 'FETCHING_MOVIES';
// export const UPDATE_MOVIES = 'UPDATE_MOVIES';
// export const GET_TOTAL_PAGE = 'GET_TOTAL_PAGE';


// 'ERROR_GET_MOVIES'
// 'GET_BY_TYPE_MOVIES'
// ERROR_GET_MOVIES
// GET_GENRES_LIST
// ERROR_GET_GENRES
// TOGGLE_DROP_DOWN
// LOGOUT
// ERROR_DELETE_SESSION
// CHANGE_PAGE
// GET_TOTAL_PAGE
// CLEAR_FILTERS
// CHANGE_FILTERS
// CHECKED_GENRE
// UNCHECKED_GENRE